server:
  port: 48086

spring:
  application:
    name: SystemAdmin
  mvc:
    view:
      prefix: /
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  resources:
    static-locations:
      - "file:/opt/static/"
      - "classpath:/static/"
  jpa:
    hibernate:
      ddl-auto: update #validate
      database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  datasource:
    username: bbtang
    password: bbtangPass4!
    url: jdbc:mysql://49.65.103.29:3306/systemAdmin?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    # com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 25
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1



management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,metrics,shutdown,mappings,conditions,trace,env,prometheus
  server:
    port: 38081
  security:
    enabled: false



mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mappers/*.xml
  #  定义所有操作类的别名所在包
  type-aliases-package: cn.dails.dao.entity
  global-config:
    db-config:
      # id-type: auto
      # field-strategy: not_empty
      #驼峰下划线转换
      # column-underline: true
      logic-delete-field: deleted
      #逻辑删除配置
      logic-delete-value: 1
      # 未删除，默认0
      logic-not-delete-value: 0
      db-type: mysql
      auto-fill: true
    refresh: true
    configuration:
      #驼峰下划线转换
      # map-underscore-to-camel-case 》 db-column-underline 为了歧义新版去掉 db-column-underline
      map-underscore-to-camel-case: true
      cache-enabled: false
      # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



logging:
  config: classpath:logback-dev.xml
  level:
    cn:
      dails:
        dao: debug
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG