server:
  port: 9091

spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: mhxysy
          uri: http://localhost:8080
          predicates:
            - Path=/api/mhxysy/**
          filters:
            - StripPrefix=2

#logging:
#  file:
#    name: D:/log/gateway.log
#  level:
#    springfox: error
#    cn.edu.sgu.www.gateway: debug